In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

import os
print(os.listdir("input"))
features=pd.read_csv('input/DATAA.csv')

['00 train test valid Code For Exergy.ipynb', '00 train test valid Code For HHV.ipynb', '00 train test valid Code For PCC.ipynb', '00 train test valid Code For Power1.ipynb', '00 train test valid First 8 Algorithm hydrogen.ipynb', '00 train test valid hydrogen2.ipynb', '00 train test valid Power 2 MLP-XGB.ipynb', 'DATAA.csv', 'DataJP.csv']

In [2]:
features.head(5)

,Carbon,Hydrogen,Nitrogen,Sulfur,Oxygen,Ash,Air_MF,Steam_MF,PYROL_T,GASIF_T,Water_WGS,CAOH2,CARBONAT_T,LNG_MF,H2_P,CO2_P,POWER,PCC_P,EXERGY,HHV
0,47.9,6.3,0.32,0.01,44.27,1.2,300,500,640,750,700,1000,310,700,82.575165,382.298959,229.700598,1350.8379,331.935067,9115.993
1,47.9,6.3,0.32,0.01,44.27,1.2,300,500,640,750,700,1000,310,800,82.575165,437.164581,250.991074,1350.8379,331.935067,9115.993
2,47.9,6.3,0.32,0.01,44.27,1.2,300,500,640,750,700,1000,310,900,82.575165,492.030203,272.277819,1350.8379,331.935067,9115.993
3,47.9,6.3,0.32,0.01,44.27,1.2,300,500,640,750,700,1000,310,1000,82.575165,546.895824,293.561646,1350.8379,331.935067,9115.993
4,47.9,6.3,0.32,0.01,44.27,1.2,300,500,640,750,700,1000,310,1100,82.575165,601.761446,314.843148,1350.8379,331.935067,9115.993

In [3]:
data= features.sample(n=140000, replace=True,random_state=40)
data.head()
data.describe()

,Carbon,Hydrogen,Nitrogen,Sulfur,Oxygen,Ash,Air_MF,Steam_MF,PYROL_T,GASIF_T,Water_WGS,CAOH2,CARBONAT_T,LNG_MF,H2_P,CO2_P,POWER,PCC_P,EXERGY,HHV
count,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000,140000.000000
mean,50.738623,6.354265,0.687168,0.317470,36.156761,5.433666,376.884071,764.412886,493.231836,839.236007,884.994914,1941.837707,501.751771,1059.741429,130.565490,531.343043,375.742259,2619.477577,451.223392,8836.950341
std,12.523422,1.104779,0.675425,0.600815,13.855931,6.610369,58.779980,205.099397,88.680755,70.064499,148.204326,735.310392,126.523924,225.789181,41.562995,163.766949,70.821776,991.863436,86.526474,2041.199849
min,28.850000,3.685500,0.000000,0.000000,3.160000,0.200000,300.000000,500.000000,370.000000,700.000000,610.000000,308.000000,310.000000,700.000000,36.978561,0.029274,171.047550,374.100451,247.257424,4366.627840
25%,45.850000,5.850000,0.350000,0.000000,37.121700,2.870000,335.000000,570.000000,405.000000,775.000000,750.000000,1250.000000,374.000000,900.000000,105.589778,437.164581,325.706679,1688.547370,385.403627,7573.744560
50%,47.900000,6.130000,0.400000,0.000000,42.000000,3.200000,370.000000,790.000000,490.000000,850.000000,860.000000,1900.000000,502.000000,1100.000000,125.937557,546.895824,375.722065,2566.592000,441.889941,8350.720720
75%,50.220000,7.430000,1.280000,0.110000,44.800000,7.100000,440.000000,900.000000,550.000000,900.000000,950.000000,2500.000000,630.000000,1300.000000,146.569280,656.627068,428.505916,3377.094740,509.127734,9240.497860
max,80.270000,8.131200,3.685500,1.813500,45.430000,41.500000,475.000000,1100.000000,640.000000,975.000000,1200.000000,3400.000000,694.000000,1400.000000,303.375230,766.358811,573.076617,4592.848850,731.382652,15584.033500

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X = data[["Carbon", "Hydrogen","Nitrogen","Sulfur","Oxygen","Ash","Air_MF","Steam_MF","PYROL_T", "GASIF_T","Water_WGS","CAOH2","CARBONAT_T", "LNG_MF"]]
y = data[['H2_P', 'CO2_P', 'POWER', 'PCC_P', 'EXERGY', 'HHV']]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [7]:
from sklearn.ensemble import RandomForestRegressor

In [8]:
rf_model = RandomForestRegressor(random_state=42)

In [9]:
models = {}
for target_column in y.columns:
    model = RandomForestRegressor()
    model.fit(X_train, y_train[target_column])
    models[target_column] = model

In [10]:
variable_intervals = {
    'Carbon': (40, 44),
    'Hydrogen': (2, 5),
    'Nitrogen': (0, 1),
    'Sulfur': (0, 1),
    'Oxygen': (30, 33),
    'Ash': (1, 2),
    'Air_MF': (350, 353),
    'Steam_MF': (100, 102),
    'PYROL_T': (251, 253),
    'GASIF_T': (600, 602),
    'Water_WGS': (100, 102),
    'CAOH2': (200, 202),
    'CARBONAT_T': (300, 303),
    'LNG_MF': (50, 52),
    }

In [11]:
def optimize_target(target_column):
    best_output = float('-inf')
    best_variables = None
    
    # Iterate over all possible combinations of variables within the intervals
    for carbon in range(*variable_intervals['Carbon']):
        for hydrogen in range(*variable_intervals['Hydrogen']):
            for nitrogen in range(*variable_intervals['Nitrogen']):
                for sulfur in range(*variable_intervals['Sulfur']):
                    for oxygen in range(*variable_intervals['Oxygen']):
                        for ash in range(*variable_intervals['Ash']):
                            for air_mf in range(*variable_intervals['Air_MF']):
                                for steam_mf in range(*variable_intervals['Steam_MF']):
                                    for pyrol_t in range(*variable_intervals['PYROL_T']):
                                        for gasif_t in range(*variable_intervals['GASIF_T']):
                                            for water_wgs in range(*variable_intervals['Water_WGS']):
                                                for caoh2 in range(*variable_intervals['CAOH2']):
                                                    for carbonat_t in range(*variable_intervals['CARBONAT_T']):
                                                        for lng_mf in range(*variable_intervals['LNG_MF']):
                                                             # Make predictions using the trained model
                                                            output = models[target_column].predict([[carbon, hydrogen, nitrogen, sulfur, oxygen, ash, air_mf, steam_mf, pyrol_t, gasif_t, water_wgs, caoh2, carbonat_t, lng_mf]])
                                        
                                                            # Check if the output is better than the current best output
                                                            if output > best_output:
                                                                best_output = output
                                                                best_variables = (carbon, hydrogen, nitrogen, sulfur, oxygen, ash, air_mf, steam_mf, pyrol_t, gasif_t, water_wgs, caoh2, carbonat_t, lng_mf)
    
    # Return the best output and the corresponding variables
    return best_output, best_variables

# Optimize each target value within the specified intervals

In [ ]:
optimized_results = {}
for target_column in y.columns:
    best_output, best_variables = optimize_target(target_column)
    optimized_results[target_column] = {'Best Output': best_output, 'Best Variables': best_variables}

# Print the optimized results
for target_column, result in optimized_results.items():
   print(f'Optimized result for {target_column}: {result}')

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Evaluate the performance of the trained models using the testing data
evaluation_results = {}
for target_column, model in models.items():
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test[target_column], y_pred)
    mse = mean_squared_error(y_test[target_column], y_pred)
    r2 = r2_score(y_test[target_column], y_pred)
    evaluation_results[target_column] = {'MAE': mae, 'MSE': mse, 'R2 Score': r2}

# Print the evaluation results
for target_column, result in evaluation_results.items():
    print(f'Evaluation results for {target_column}: {result}')

Evaluation results for H2_P: {'MAE': 0.712633958766488, 'MSE': 1.6545999164450076, 'R2 Score': 0.999039387382835}
Evaluation results for CO2_P: {'MAE': 2.195542098982241, 'MSE': 94.52201304613293, 'R2 Score': 0.9965052420140178}
Evaluation results for POWER: {'MAE': 0.2725663863988209, 'MSE': 1.9991296337149635, 'R2 Score': 0.9996018153009206}
Evaluation results for PCC_P: {'MAE': 0.11679532060559826, 'MSE': 0.7728319436678831, 'R2 Score': 0.9999992140357445}
Evaluation results for EXERGY: {'MAE': 0.6413225150045961, 'MSE': 1.9993876655006597, 'R2 Score': 0.9997316858503416}
Evaluation results for HHV: {'MAE': 2.0100068053541413, 'MSE': 27.284348015407804, 'R2 Score': 0.9999933886439725}

In [16]:
new_data = [[0.3, 150, 100, 800, 700, 0.1, 100, 800, 200,100,100,100,100,100]]  # Example new data
predictions = {}
for target_column, model in models.items():
    predictions[target_column] = model.predict(new_data)

# Print the predictions
for target_column, prediction in predictions.items():
    print(f'Predictions for {target_column}: {prediction}')

Predictions for H2_P: [41.94622787]
Predictions for CO2_P: [382.29895938]
Predictions for POWER: [182.60865223]
Predictions for PCC_P: [401.07074158]
Predictions for EXERGY: [328.42304212]
Predictions for HHV: [5291.5649977]

c:\Users\mostafa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\mostafa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\mostafa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\mostafa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\mostafa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
c:\Users\mostafa\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(